bench target:
  make SRC={{target}}.opt.cxx DST={{target}}.opt.out
  make SRC={{target}}.simp.cxx DST={{target}}.simp.out
  hyperfine --warmup 2 ./{{target}}.opt.out ./{{target}}.simp.out
  make clean