make-with-debuginfo target:
  make SRC={{target}}.simp.cxx DST={{target}}.simp.out USE_RC=0 DEBUGINFO=1
  make SRC={{target}}.opt.cxx DST={{target}}.opt.out USE_RC=0 DEBUGINFO=1

make target:
  make SRC={{target}}.simp.cxx DST={{target}}.simp.out USE_RC=0 DEBUGINFO=0
  make SRC={{target}}.opt.cxx DST={{target}}.opt.out USE_RC=0 DEBUGINFO=0

bench target: (make target)
  hyperfine --warmup 5 --runs 20 \
      ./{{target}}.simp.out \
      ./{{target}}.opt.out \
      --export-csv {{target}}.csv

clean:
  rm -rf *.out *.csv *.o

dist-clean: clean
  rm -rf *.simp.cxx *.opt.cxx *.llir
